source 'https://rubygems.org'

gem 'actionview', require: 'action_view'
gem 'activerecord', '~> 5', require: 'active_record'
gem 'activesupport', require: 'active_support/all'
gem 'awesome_print'
gem 'byebug'
gem 'colored'
gem 'hashdiff'
gem 'highline', require: 'highline/import'
gem 'hirb'
gem 'map_by_method'
gem 'mechanize'
gem 'nokogiri'
gem 'pry'
gem 'rake'
gem 'sqlite3'
gem 'terminal-table'
